### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MosheBerman** [DanielSmith1239/KosherSwift#2]
KosherSwift is port of KosherCocoa, which is a port of KosherJava. Because the original Java library is licensed under a modified LGPL license, the derivative works need to follow the same rules. (I've reached out to the original author of the Java library for clarification, but I'm pretty sure this is the case.)

Can you change the license from MIT to LGLP?

**Comment by DanielSmith1239** [comment]
Sure, will do.

**Comment by DanielSmith1239** [comment]
Changed license to "GNU LESSER GENERAL PUBLIC LICENSE"
